# Generated by Django 2.0.8 on 2018-10-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20180915_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
